name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '50 5 * * *'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Setup | Std
        run: rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
      - name: Setup | Default to stable
        run: rustup default stable
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Build | Clippy
        run: cargo clippy --no-deps --workspace
      - name: Build | Compile
        run: cargo build --workspace
